vim.g.mapleader = ' '
vim.keymap.set('n', 'q', vim.cmd.q)
vim.keymap.set('n', 'w', vim.cmd.w)
vim.keymap.set('n', 'x', vim.cmd.x)
vim.keymap.set('n', 'Q', vim.cmd['q!'])
vim.keymap.set('n', '<leader>w', vim.cmd.w)
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { silent = true })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { silent = true })
vim.keymap.set('n', '<leader>d', function() vim.diagnostic.open_float({ focus = true }) end)
vim.keymap.set({ 'n', 'v' }, '<leader>y', '"+y')
vim.keymap.set('n', '<leader>s', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set('n', '<C-d>', '<C-d>zz')
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('n', 'N', 'Nzzzv')
