# rose-pine flavor by Mintass: https://github.com/Mintass/rose-pine.yazi
[flavor]
dark = "rose-pine"
light = "rose-pine"

# transparent background, regardless of flavor
[app]
overall = { bg = "reset" }

[status]
overall = { bg = "reset" }
